# Site
name: "umrah.lk"
title: "Umrah.lk"
description: "Embarking on the transformational travels of Umrah is a holy calling for all Sri Lankan Muslims. Regardless of financial position, assisting everyone to undertake this at least once in their lives is our deepest vision and mission."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
domain: 'umrah.lk'
url: 'https://umrah.lk'
baseurl: ''
google_analytics: 'G-RE843W4H72'
disqus: 'umrah-lk'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  zum:
    name: Zumry
    display_name: Zumry
    gravatar: 
    email: mail2umrah.lk@gmail.com
    web: https://www.umrah.lk
    twitter: https://twitter.com/umrahlk
    description: "Author of Umrah.lk"
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
